<script src="https://use.fontawesome.com/2e576da815.js"></script>

<div style="text-align: left;"><img src="https://www.juliabox.org/assets/img/juliacloudlogo.png" style="margin: 0px 0px 0px 0px; padding-right: 20px;width: 80px; float: left;" title="" alt="" /></div>
<img src="http://dmkpress.com/images/cms/thumbs/a5b0aeaa3fa7d6e58d75710c18673bd7ec6d5f6d/978-5-97060-370-3_270_369__100.jpg" style="margin: 0px 0px 5px 20px; width: 100px; float: right;" title="" alt="" />
Всестороннее введение в новый язык программирования для научно-технических вычислений [Julia](http://julialang.org/) в книге Малколма Шеррингтона, Packt Publishing, июль 2015.

<h1>Осваиваем язык Julia</h1><br />

Совершенствование мастерства в области аналитики и программирования при помощи Julia в целях решения задач комплексной обработки данных
<div style="text-align: left;font-size:8pt;padding-top:10px;">Программный код Julia (v0.4.5) протестирован в Windows 8.1/10 и Linux/Lubuntu 16.4</div>
<div style="text-align: left;"><h1>Глава 4. Функциональная совместимость</h1></div>

# 1. Взаимодействие с другими программными средами 

## Обращение к функциям на C и Fortran

<pre>
Образец вызова

ccall((символ, библиотека), ТипВозвращаемогоЗначения, (ТипАрг1, ...), Арг1, ...)
</pre>

<i class="fa fa-linux" aria-hidden="true"></i>
<i class="fa fa-apple" aria-hidden="true"></i>

In [ ]:
x = ccall( (:rand, "libc"), Int32, ())

In [ ]:
x = ccall( (:rand, "libc"), Int32, ())

<i class="fa fa-windows" aria-hidden="true"></i>

In [2]:
function lcg_rand()
  seed = ccall( (:GetTickCount, "kernel32"), stdcall, Int32, () );
  ((seed * 214013 + 2531011) >> 16) & 0x7fff
end

lcg_rand (generic function with 1 method)

In [3]:
lcg_rand() 

6694

In [4]:
lcg_rand()  

9144

<i class="fa fa-linux" aria-hidden="true"></i>
<i class="fa fa-apple" aria-hidden="true"></i>

In [ ]:
home = ccall( (:getenv, "libc"), Ptr{UInt8},(Ptr{UInt8},), "HOME")

jmods = string(bytestring(home),"/julia_projects");
push!(LOAD_PATH, jmods);

LOAD_PATH

<i class="fa fa-windows" aria-hidden="true"></i>
<i class="fa fa-linux" aria-hidden="true"></i>
<i class="fa fa-apple" aria-hidden="true"></i>

In [8]:
jl_projs = joinpath(homedir(),"julia_projects");
push!(LOAD_PATH, jl_projs)

3-element Array{AbstractString,1}:
 "C:\\Julia-0.4.5\\local\\share\\julia\\site\\v0.4"
 "C:\\Julia-0.4.5\\share\\julia\\site\\v0.4"       
 "C:\\Users\\labor\\julia_projects"                

In [6]:
# удалить последний элемент
pop!(LOAD_PATH);

LOAD_PATH

1-element Array{AbstractString,1}:
 "C:\\Julia-0.4.5\\local\\share\\julia\\site\\v0.4"

In [7]:
# инициализировать стандартными значениями
LOAD_PATH = AbstractString[]
push!(LOAD_PATH, "C:\\Julia-0.4.5\\local\\share\\julia\\site\\v0.4");
push!(LOAD_PATH,  "C:\\Julia-0.4.5\\share\\julia\\site\\v0.4");

LOAD_PATH   

2-element Array{AbstractString,1}:
 "C:\\Julia-0.4.5\\local\\share\\julia\\site\\v0.4"
 "C:\\Julia-0.4.5\\share\\julia\\site\\v0.4"       

### Отображение на C-типы

<i class="fa fa-linux" aria-hidden="true"></i>
<i class="fa fa-apple" aria-hidden="true"></i>

<pre>ccall((:pow,"libmymath.so"),Float64,(Float64,Int32),x,n)</pre>

In [12]:
pow(x,n) = ccall((:pow,"libmymath.so"),Float64,(Float64,Int32), (convert(Float64,x),convert(Int32,n)))

pow (generic function with 1 method)

In [ ]:
pow(3,3)

#### Соотнесения типов

<pre>
(unsigned) char   # => typealias cuchar UInt8
(signed)   short  # => typealias cshort Int16 

char*              => Ptr(UInt8)
char** или *char[] => Ptr{Ptr{UInt8}}
</pre>

### Вызов подпрограммы на Fortran

<i class="fa fa-linux" aria-hidden="true"></i>
<i class="fa fa-apple" aria-hidden="true"></i>

In [ ]:
#
# compute_dot.jl
#
# Вызов программы на Fortran
# для Unix-подобных ОС

function compute_dot(DX::Vector{Float64},DY::Vector{Float64})
  assert(length(DX) == length(DY))
  n = length(DX)
  incx = incy = 1
    product = ccall((:ddot_, "/usr/lib/lapack/liblapack.so.3.6.0"),
    Float64,
    (Ptr{Int32}, Ptr{Float64}, Ptr{Int32}, Ptr{Float64}, Ptr{Int32}),
    &n, DX, &incx, DY, &incy)
  return product
end

### Вызов утилиты curl для получения веб-страницы

<pre>
# https://curl.haxx.se/libcurl/c/curl_easy_perform.html

# образец вызова на C

CURL *curl = curl_easy_init();
if(curl) {
  CURLcode res;
  curl_easy_setopt(curl, CURLOPT_URL, "http://example.com");
  res = curl_easy_perform(curl);
  curl_easy_cleanup(curl);
}
</pre>

In [ ]:
#
# call_curl.jl
#
# В ячейке результатов появится HTML-код страницы julialang.com

const CURLOPT_URL = 10002
const CURLOPT_FOLLOWLOCATION = 52;
const CURLE_OK = 0

jlo = "http://julialang.org";

curl = ccall( (:curl_easy_init, "libcurl"), Ptr{UInt8}, ())

ccall((:curl_easy_setopt, "libcurl"), Ptr{UInt8}, (Ptr{UInt8}, Int, Ptr{UInt8}), curl, CURLOPT_URL, jlo.data)
ccall((:curl_easy_perform,"libcurl"), Ptr{UInt8}, (Ptr{UInt8},), curl);
ccall((:curl_easy_cleanup,"libcurl"), Ptr{UInt8}, (Ptr{UInt8},), curl);

## Язык Python

In [35]:
using PyCall

@pyimport scipy.optimize as so
@pyimport scipy.integrate as si

In [2]:
so.ridder(x -> x*cos(x), 1, pi) 

1.5707963267953966

In [3]:
si.quad(x -> x*sin(x), 1, pi)[1] 

2.840423974650036

In [36]:
@pyimport matplotlib.pyplot as plt

x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
plt.plot(x, y, color="red", linewidth=2.0, linestyle="--")

1-element Array{Any,1}:
 PyObject <matplotlib.lines.Line2D object at 0x00000000011E4198>

In [37]:
# график будет выведен в "родном" окне библиотеки matplotlib
plt.show()

### Обращение к API из C

<pre>
#include <julia.h>
#define LIBEXEC "/home/malcolm/julia/usr/lib"
int main() {
  jl_init(LIBEXEC);
  JL_SET_STACK_BASE;
  jl_eval_string("println(pi)");
  return 0;
}
</pre>

<pre>
export JH=/home/malcolm/julia
export LD_LIBRARY_PATH=$JH/usr/lib
gcc -o pi -I$JH/src -I$JH/src/support
              -I$JH/usr/include -L$JH/usr/lib -ljulia pi.c

./pi ; # => π = 3.1425926535897 ...
</pre>

<pre>
#include <stdio.h>
#include <math.h>
#include <julia.h>
#define LIBEXEC "/home/malcolm/julia/usr/lib"
int main() {
  jl_init(LIBEXEC);
  JL_SET_STACK_BASE;
  jl_function_t *powf = jl_get_function(jl_base_module, "^");
  jl_value_t *arg1 = jl_box_float64(M_PI);
  jl_value_t *arg2 = jl_box_float64(2.0);
  jl_value_t *rtv = jl_call2(powf,arg1,arg2);
  JL_GC_PUSH1(&rtv);
  if (jl_is_float64(rtv)) {
    double e_pi = jl_unbox_float64(rtv);
    printf("pi (в квадрате) = %f\n", e_pi);
  }
  else {
    printf("Ой, что-то пошло не так!\n");
  }
  JL_GC_POP();
  return 0;
}
</pre>