<div style="text-align: left;"><img src="https://www.juliabox.org/assets/img/juliacloudlogo.png" style="margin: 0px 0px 0px 0px; padding-right: 20px;width: 80px; float: left;" title="" alt="" /></div>
<img src="http://dmkpress.com/images/cms/thumbs/a5b0aeaa3fa7d6e58d75710c18673bd7ec6d5f6d/978-5-97060-370-3_270_369__100.jpg" style="margin: 0px 0px 5px 20px; width: 100px; float: right;" title="" alt="" />
Всестороннее введение в новый язык программирования для научно-технических вычислений [Julia](http://julialang.org/) в книге Малколма Шеррингтона, Packt Publishing, июль 2015.

<h1>Осваиваем язык Julia</h1><br />

Совершенствование мастерства в области аналитики и программирования при помощи Julia в целях решения задач комплексной обработки данных
<div style="text-align: left;font-size:8pt;padding-top:10px;">Программный код Julia (v0.4.5) протестирован в Windows 8.1/10 и Linux/Lubuntu 16.4</div>
<div style="text-align: left;"><h1>Глава 2. Разработка на Julia</h1></div>


# Массивы


In [2]:
A = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]

15-element Array{Int64,1}:
   0
   1
   1
   2
   3
   5
   8
  13
  21
  34
  55
  89
 144
 233
 377

In [3]:
typeof(A)

Array{Int64,1}

In [9]:
A = [1:10;]

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [5]:
B = [1:3:15]

5-element Array{Int64,1}:
  1
  4
  7
 10
 13

In [10]:
C = [1:0.5:5]

9-element Array{Float64,1}:
 1.0
 1.5
 2.0
 2.5
 3.0
 3.5
 4.0
 4.5
 5.0

In [12]:
A = round(Int64,zeros(15)); B = round(Int64,ones(15)); C = rand(1:100,15);
A,B,C

([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[99,30,13,91,40,61,50,64,73,28,31,40,49,100,83])

In [29]:
A = Array(Int64,15); A[1]=0;A[2]=1;[A[i] = A[i-1] + A[i-2] for i = 3:length(A)]

13-element Array{Any,1}:
   1
   2
   3
   5
   8
  13
  21
  34
  55
  89
 144
 233
 377

In [30]:
A = Int64[];
push!(A,1); push!(A,2); push!(A,3) 
A

3-element Array{Int64,1}:
 1
 2
 3

In [40]:
A = [1,2,3]; A

3-element Array{Int64,1}:
 1
 2
 3

In [37]:
pop!(A); A

2-element Array{Int64,1}:
 1
 2

In [39]:
A = [1 2 3]; A

1x3 Array{Int64,2}:
 1  2  3

In [40]:
A = [1 2 3; 4 5 6] 

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [6]:
A = [1 2 3; 4 5 6];
for i in (1:length(A)) @printf("%1d: %1d\n", i, A[i]); end

1: 1
2: 4
3: 2
4: 5
5: 3
6: 6


In [8]:
A[1,2],
A[2],   
A[5]    

(2,4,3)

In [17]:
B = reshape(A,3,2)

3x2 Array{Int64,2}:
 1  5
 4  3
 2  6


## Операции на матрицах


In [18]:
C = transpose(B); C

2x3 Array{Int64,2}:
 1  4  2
 5  3  6

In [16]:
A + C

2x3 Array{Int64,2}:
 2  6   5
 9  8  12

In [17]:
A*B

2x2 Array{Int64,2}:
 15  29
 36  71

In [18]:
A / C

2x2 Array{Float64,2}:
 0.332273  0.27663 
 0.732909  0.710652


## Поэлементные операции


In [19]:
A .* C

2x3 Array{Int64,2}:
  1   8   6
 20  15  36

In [20]:
A ./ C

2x3 Array{Float64,2}:
 1.0  0.5      1.5
 0.8  1.66667  1.0

In [50]:
A .== C

2x3 BitArray{2}:
  true  false  false
 false  false   true


## Простая марковская цепь – кошки и мышки


In [51]:
I = eye(4);

P = [0 0 .5 0; 0 0 1 0; .25 .25 0 .25; 0 0 .5 0];
ep = [0 1 0 0]*inv(I - P)*[1,1,1,1];

println ("Ожидаемое время жизни для мышки равно $ep тактов")

Ожидаемое время жизни для мышки равно [4.5] тактов
